### PR TITLE
EPA datasets

### PR DESCRIPTION
**Pull request by danielfdsilva**
This PR contains a first pass at adding the EPA datasets as described in https://github.com/NASA-IMPACT/veda-data-pipelines/issues/155.

TODO:
- [x] Review dataset grouping. I tried to [group the datasets logically](https://github.com/NASA-IMPACT/veda-data-pipelines/issues/155#issuecomment-1243976868) but this grouping needs to be reviewed.
- [x] Add relevant cover images to each dataset.
- [x] Review dataset title (currently kebab-case).
- [x] Add dataset description.
- [x] Review dataset layer title and description (were copied from the api and could use better copy for the UI)
- [x] Setup correct legend units. Currently shows the values for min/max coming from the api and that does not help interpreting the data. I don't know how to interpret the unit from the link @aboydnw [shared](https://www.epa.gov/ghgemissions/gridded-2012-methane-emissions#data) (Mg a<sup>-1</sup> km<sup>-2</sup>). How do we convert a max of `202 263 465 295 872` to those units?
- [x] Review `rescale` value. Currently set to be the `min/max` from the api, which means no rescaling. Not sure if this is good to interpret the data or even if all datasets should share the values.

@aboydnw Would you be able to help with the answers to these questions?

cc @slesaad

### CODE REVIEW

**Comment by aboydnw** [comment]
@danielfdsilva thanks for compiling this list. I added some details below.

### Dataset grouping and titles
Well, I originally thought the grouping was good. Then I started reading the paper linked to the original data. I think this would probably be a better original grouping. Sorry about the late changes.

EPA - Agriculture
EPA-annual-emissions_4B_Manure_Management
EPA-monthly-emissions_4B_Manure_Management
EPA-annual-emissions_4C_Rice_Cultivation
EPA-monthly-emissions_4C_Rice_Cultivation
EPA-annual-emissions_4A_Enteric_Fermentation
EPA-annual-emissions_4F_Field_Burning
EPA-monthly-emissions_4F_Field_Burning

EPA - Natural Gas Systems
EPA-annual-emissions_1B2b_Natural_Gas_Processing
EPA-annual-emissions_1B2b_Natural_Gas_Production
EPA-monthly-emissions_1B2b_Natural_Gas_Production
EPA-annual-emissions_1B2b_Natural_Gas_Transmission
EPA-annual-emissions_1B2b_Natural_Gas_Distribution

EPA - Petroleum Systems
EPA-annual-emissions_1B2a_Petroleum
EPA-monthly-emissions_1B2a_Petroleum

EPA - Coal Mines
EPA-annual-emissions_1B1a_Coal_Mining_Underground
EPA-annual-emissions_1B1a_Coal_Mining_Surface
EPA-annual-emissions_1B1a_Abandoned_Coal

EPA - Waste
EPA-annual-emissions_6B_Wastewater_Treatment_Domestic
EPA-annual-emissions_6B_Wastewater_Treatment_Industrial
EPA-annual-emissions_6A_Landfills_Industrial
EPA-annual-emissions_6A_Landfills_Municipal
EPA-annual-emissions_6D_Composting

EPA - Other
EPA-annual-emissions_2B5_Petrochemical_Production
EPA-annual-emissions_2C2_Ferroalloy_Production
EPA-annual-emissions_1A_Combustion_Mobile
EPA-annual-emissions_1A_Combustion_Stationary
EPA-monthly-emissions_1A_Combustion_Stationary
EPA-annual-emissions_5_Forest_Fires
EPA-annual-emissions_5_Forest_Fire
EPA-daily-emissions_5_Forest_Fires

### Dataset cover images

EPA - Agriculture
james-baltz-jAt6cN6zl8M-unsplash

EPA - Natural Gas Systems
american-public-power-association-TF-DL_2L1JM-unsplash

EPA - Petroleum Systems
patrick-hendry-6xeDIZgoPaw-unsplash

EPA - Coal Mines
dominik-vanyi-Mk2ls9UBO2E-unsplash (1)

EPA - Waste
antoine-giret-7_TSzqJms4w-unsplash

EPA - Other
documerica-EjSw6WdnLRA-unsplash

### Add dataset description
To start, maybe we can use this description for all the EPA datasets.

> ## Gridded 2012 Methane Emissions

> A team at Harvard University along with EPA and other coauthors developed a gridded inventory of U.S. anthropogenic methane emissions with 0.1° x 0.1° spatial resolution, monthly temporal resolution, and detailed scale-dependent error characterization. The inventory is designed to be consistent with the 2016 U.S. EPA [Inventory of U.S. Greenhouse Gas Emissions and Sinks](https://www.epa.gov/ghgemissions/us-greenhouse-gas-inventory-report-1990-2014) estimates for the year 2012, which presents national totals for different source types. The gridded inventory was developed using a wide range of databases at the state, county, local, and point source level to allocate the spatial and temporal distribution of emissions for individual source types.

> This data can be used by researchers to better compare the national-level inventory with measurement results that may be at other scales. Users of this gridded inventory are asked to cite the original reference (Maasakkers et al., 2016) in their publications. Error estimates are given in that reference.

> [Paper: Maasakkers et. al. 2016, A Gridded National Inventory of U.S. Methane Emissions](https://www.epa.gov/ghgemissions/gridded-2012-methane-emissions#paper)

### Review dataset layer title and description
For this first iteration, let's just remove the "Gridded 2012 EPA Methane Emissions - " from each layer title since I included that in the dataset overview above. We'll include the layer title and description as something for the GHG team and Alexey to review. 
Side note, I wasn't able to see the full layer title in the UI. Hovering didn't bring up any tooltip or anything like that. Wasn't sure if that was an issue just with the netlify preview or not.

### Legend Units & Rescale values

This one confuses me too. I see the maximum on the scale in the thousands, but don't see any points on the map that come close to the maximum (on any of the maps). Are we sure the max is accurate? What do the maps look like if we set the min/max of 0-10 like most of the maps in the [paper](https://pubs.acs.org/doi/10.1021/acs.est.6b02878) look?

**Comment by danielfdsilva** [comment]
@aboydnw Thank you for the images. They look good! For future reference it would be good to mention the author and a url. I was able to find the images in unsplash and get the needed values.

Datasets were regrouped according to your list and It's much more pleasing.

We can't just use 0-10 since the values are in the billions. The values in the paper are probably something like 10 (millions of some unit). We need some more info here.

**Comment by slesaad** [comment]
hey @danielfdsilva , sorry that I accidentally made a commit to your branch instead of a new branch that i was creating to test these values (my vscode messed up). But at least we can look at the [visualization in this one dataset](https://deploy-preview-109--visex.netlify.app/eis/datasets/epa-agriculture/explore?position=-103.6651%7C36.1008%7C3.06&datetime=2012-01-01T00%3A00%3A00.000Z&layer=epa-annual-emissions_4a_enteric_fermentation) and maybe it's better than the current one?

i was gonna revert the changes, but i'm gonna leave it here anyway since we'll have to change the rescale values anyway. but let me know if you want me to revert it!

sorry again! 😅

**Comment by aboydnw** [comment]
+1 @slesaad if we can play around with the values a bit to get something presentable, that would be a great next step. 

Then it would be easier to sit down with Lesley and Kevin to tweak from there. I can work to get something setup, I would imagine sometime next week. 

In the meantime, if we get to something similar to the dataset you linked for all the EPA datasets, I would be game for merging this and pushing to production with the rest of the content.

What do you think @danielfdsilva ?

**Comment by slesaad** [comment]
@danielfdsilva I've opened up a PR against this branch with the updated rescale, nodata and legend values. @aboydnw and I think that it's more presentable that way. please check it out!

**Comment by danielfdsilva** [comment]
@aboydnw @slesaad going to go ahead and merge this since #111 (which branched from this), was good and approved.

**Pull request merged**
