### PR TITLE
Add nodata masks for TWS datasets and un-reverse colormap

### PR DESCRIPTION
**Pull request by anayeaye**
## What
- added nodata values to tws dataset config files
- changed colormap to rdylbu to agree with legend stops

## How tested
Served locally and reviewed on localhost. While the change was minor I ended up needing to rerun the setup to run successfully.
```
git submodule update --init --recursive
./.delta/setup
```

### CODE REVIEW

**Comment by anayeaye** [comment]
@sahmad3 - I think these are the changes you were asking for: using the regular rdylbu colormap and masking nodata values. I think this is the desired configuration? Please feel free to take over this PR and/or selectively use the suggested changes.
tws-cfg
?

**Comment by sahmad3** [comment]
@anayeaye  thanks, nodata looks good, but the legend at the bottom right should be reversed (red for -ve and blue for +ve). I was trying that by reversing the colors in 'stops' but that was causing fatal error. Any other way to reverse the legend?

**Comment by sahmad3** [comment]
@anayeaye  I worked around that issue of reversing colors on the colorbar by switching the min max values. So the values correspond to color now but vary from 1(blue) to -1 (red). This is fine for now, but let me know if you can find a better solution

**Comment by anayeaye** [comment]
@sahmad3 - I misunderstood. The anomaly colormap (and legend) should be the reverse of the trend?
tws-cfg-2

**Comment by sahmad3** [comment]
@anayeaye no both should follow same colors (red for -ve values, blue for +ve values).
Your anomaly colormap now looks perfect. Can we do the same for trend colormap? Sorry for any confusion on this

**Comment by anayeaye** [comment]
🙃 @sahmad3 I think this might be it:
tws-cfg-3

**Comment by sahmad3** [comment]
@anayeaye  yep this is it!

**Comment by anayeaye** [comment]
@sahmad3 I made the change the same as you did--by reversing the stops in the legend. Maybe there was a stray formatting error like an extra space somewhere? I also stopped the server and ran `yarn clean`, if that helps any.

There is one additional change in this branch: I expanded the datetime format in the compare panel for the anomaly dataset so that the text showed two different dates for the same year.

**Comment by sahmad3** [comment]
thanks @anayeaye ! I have a few minor changes to the text blocks that I will commit here ingesting your edits.

**Comment by sahmad3** [comment]
@anayeaye I have added another commit #82 ingesting all the edits. Hoping it can go to production

**Comment by anayeaye** [comment]
This PR is no longer needed, all fixes are in #82

**Pull request closed without merging**
