### PR TITLE
UI update

### PR DESCRIPTION
**Pull request by danielfdsilva**
- Updates the api endpoints to `https://staging-*.delta-backend.com`
- Updates delta-ui to the latest `main`.

**Missing:**
- [x] Agriculture > [GEOGLAM dataset is missing cover](https://deploy-preview-112--visex.netlify.app/agriculture/datasets/geoglam)
- [x] Agriculture > [GEOGLAM description too long](https://deploy-preview-112--visex.netlify.app/agriculture/datasets/geoglam)
- [x] Biomass > [discovery missing description](https://deploy-preview-112--visex.netlify.app/biomass/discoveries/biomass-harmonization-activity)
- [x] Biomass > [discovery missing main title in the MDX (open discovery)](https://deploy-preview-112--visex.netlify.app/biomass/discoveries/biomass-harmonization-activity)
- [x] EIS > [discovery missing description](https://deploy-preview-112--visex.netlify.app/eis/discoveries/sea-ice-thickness)
- [ ] Ocean/Water > [dataset has a very poor description](https://deploy-preview-112--visex.netlify.app/water-quality/datasets/npp)

### CODE REVIEW

**Comment by hanbyul-here** [comment]
Functionally, everything looks great!
are we planning to replace these missing bg-image etc.? if not, wouldn't it be better to just show an empty background instead for public? 

Screen Shot 2022-09-16 at 8 54 19 AM

**Review by hanbyul-here — APPROVED** [review]

**Comment by slesaad** [comment]
Also, there are so many missing dataset descriptions. We could probably come up with one-line descriptions for them at least.
Images recommendations:
sea ice thickness: https://unsplash.com/photos/bwD3GLrV4pY
gridded relative deprivation index: https://unsplash.com/photos/3VLHF9b9Plg 
nceo africa: https://unsplash.com/photos/0Ws_-v4Y_wY rotated ? or just a screenshot of the data
ocean net primary production: https://unsplash.com/photos/Ko1sGLhZm5w ?

Descriptions:
EPA categories: Might be able to pull from [here](https://pubs.acs.org/doi/10.1021/acs.est.6b02878), they have the same categories; wonder if we can copy word-by-word and cite them or have to reword the description.

**Comment by danielfdsilva** [comment]
@slesaad I can handle adding the images. If you could help with the descriptions that would be super.

I'll also compile a list of missing content so that we can track

**Comment by slesaad** [comment]
Descriptions:

**EPA agriculture**
Emissions from agriculture include enteric fermentation, manure management, rice cultivation, and field burning of agricultural residues.
**EPA Natural Gas Systems**
Emissions from Natural Gas Systems include emissions from natural gas production, processing, transmission, and distribution.
**EPA Waste**
Waste emissions include landfills, wastewater treatment, and composting.
**EPA Coal Mines**
Coal mining emissions include state-level emission estimates for underground mines and surface mines.
**EPA Petroleum Systems**
National emissions from different activities and equipment related to petroleum production, refining, and transport.
**EPA Other**
Others include emissions from Petrochemical Production, Ferroalloy Production, Combustion (Mobile and Stationary), and Forest Fires.

**Comment by aboydnw** [comment]
Also I just noticed in the demo that the EPA - Agriculture dataset is missing the dash in the title. So it reads "EPA Agriculture"  and should read "EPA - Agriculture"

**Comment by danielfdsilva** [comment]
@slesaad merged your descriptions into this. Also added the images you proposed.

**Missing:**
- [ ] Agriculture > GEOGLAM dataset is missing cover
- [ ] Agriculture > GEOGLAM description too long
- [ ] Biomass > discovery missing description
- [ ] Biomass > discovery missing main title in the MDX (open discovery)
- [ ] EIS > discovery missing description
- [ ] Ocean/Water > discovery has a very poor description

cc @aboydnw

**Comment by danielfdsilva** [comment]
Added an image for geoglam (https://unsplash.com/photos/RUj5b4YXaHE)

**Comment by danielfdsilva** [comment]
Moved the **Missing** to the issue description

**Comment by aboydnw** [comment]
@danielfdsilva I made some suggestions based on your list.
- Agriculture > [GEOGLAM description too long](https://deploy-preview-112--visex.netlify.app/agriculture/datasets/geoglam) - "Open, timely, science-driven information on crop conditions"
-  Biomass > [discovery missing description](https://deploy-preview-112--visex.netlify.app/biomass/discoveries/biomass-harmonization-activity) - "A collaborative view of global biomass"
-  Biomass > [discovery missing main title in the MDX (open discovery)](https://deploy-preview-112--visex.netlify.app/biomass/discoveries/biomass-harmonization-activity) - "Multiple Efforts to Monitor Global Tree Cover"
-  EIS > [discovery missing description](https://deploy-preview-112--visex.netlify.app/eis/discoveries/sea-ice-thickness) - "How NASA determines sea ice thickness"
-  Ocean/Water > [dataset has a very poor description](https://deploy-preview-112--visex.netlify.app/water-quality/datasets/npp) - Let's keep this for now and let Dee-Dee provide feedback/come up with a new one
- Biomass > thematic area missing description - "Monitoring Earth's forests and habitat loss"

**Comment by slesaad** [comment]
made the changes in [this PR](https://github.com/NASA-IMPACT/delta-config/pull/115)

**Review by aboydnw — APPROVED** [review]
I think this is good to go once Slesa's branch is merged in.

**Pull request merged**
