### PR TITLE
Include Co2 dataset

### PR DESCRIPTION
**Pull request by danielfdsilva**
Includes `co2-diff`, `co2-mean` and about content from the trilateral dashboard.

Related issue: https://github.com/NASA-IMPACT/veda-data-pipelines/issues/180

It also update the API endpoint to `https://dev-*.delta-backend.com` because the datasets need it.

cc @slesaad

### CODE REVIEW

**Review by aboydnw — CHANGES_REQUESTED** [review]
Overview looks good. A couple requests/questions:
1. Can we make the layer titles simply "Mean CO2" and "Difference CO2"? That will more closely mirror the trilateral dashboard.
2. Is it possible to default the date to the most recent date within the dataset? I notice that's how the trilateral dashboard is setup. In particular for this dataset, since CO2 has been increasing over the years I notice that the default date of 2015 just shows a map of all blue, since the scale is likely tailored to current levels. (Which raises a question, should we have some sort of sliding scale @ricardoduplos ? I am sure pros/cons of something like that, but for datasets like CO2 I could see it being difficult if the overall values increase over time)

**Comment by slesaad** [comment]
@danielfdsilva , could you also change the stac api url to https://5vr61n5bo5.execute-api.us-west-2.amazonaws.com (for testing purposed), this is actually the to-be staging-api

**Comment by danielfdsilva** [comment]
@slesaad Url was updated. Can we merge with this url, or do we need to wait for the new url before merging this?

@aboydnw Updated the title, and initial datetime.
It is possible to have the rescale values as a [function](https://github.com/NASA-IMPACT/delta-config/blob/develop/docs/frontmatter/layer.md#function-values) and have it return different values for different dates, but it's something that is configured and not updated through the interface.

**Comment by slesaad** [comment]
we don't want to merge it with this url; we'll need to wait for the url to be switched to the new stac api

**Comment by danielfdsilva** [comment]
Depends on #107

**Review by aboydnw — APPROVED** [review]
Content-wise looks good to me. @danielfdsilva re: the function, I'd like to explore this more so thank you for linking to the documentation. I think we're okay for now with the title and date change.

**Pull request merged**
